### ISSUE TITLE
Fix CI/CD monorepo

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#81] opened 2024-08-28 17:17 UTC
Github workflows to fix
Fix CI/CD and corresponding versions for:
Run of install, build, test, run 

- [ ] apps/mobile
- [ ] apps/website
- [ ] apps/data-backend
- [ ] packages/afk_nostr_sdk
-
- [ ] onchain/cairo
- [ ] onchain/solidity_contracts
- [ ] backend

**Comment by ScottyDavies** [comment] 2024-08-28 17:22
@MSghais can i work on this

**Comment by martinvibes** [comment] 2024-08-28 17:24
@MSghais let me work on this

**Comment by ScottyDavies** [comment] 2024-08-28 17:26
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have extensive experience in CI/CD pipelines, having optimized and maintained them across various applications and environments

### How I plan on tackling this issue
I will implement this following steps 
Audit Pipelines: 
Review current configurations for each component (install, build, test, run).
Identify Issues: 
Pinpoint failures or inefficiencies in each step for all apps and packages.
Update Scripts:
 Adjust scripts to resolve issues, ensuring compatibility with versions.
Version Management:
 Ensure all components use the correct, consistent versions and dependencies.
Test Changes: 
Validate updates in a staging environment.
Deploy and Monitor: 
Roll out changes, monitor for issues, and iterate as needed.
ETA 2-4 days

**Comment by MSghais** [comment] 2024-08-28 17:45
> I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).
> 
> ### My background and how it can be leveraged
> I have extensive experience in CI/CD pipelines, having optimized and maintained them across various applications and environments
> 
> ### How I plan on tackling this issue
> I will implement this following steps Audit Pipelines: I will review current configurations for each component (install, build, test, run). Identify Issues: Pinpoint failures or inefficiencies in each step for all apps and packages. Update Scripts: Adjust scripts to resolve issues, ensuring compatibility with versions. Version Management: Ensure all components use the correct, consistent versions and dependencies. Test Changes: Validate updates in a staging environment.
> 
> ETA 2-4 days

We need to also fix github workflow. Can you also ping me in telegram?

**Comment by ScottyDavies** [comment] 2024-08-28 18:20
Alright

**Comment by lindsaymoralesb** [comment] 2024-09-04 15:39
Hi @MSghais ! Can I hop in?

### Here's how I would tackle this issue:

**1. Review the current state:** Review the existing workflows and check the ci/cd logs under GitHub actions to spot where the issue is happening.
**2. Review project:** Identify components, dependencies, and their interaction on the ci/cd and commands (`test, run, install`, etc).
**3. Update the workflows:** Make the necessary fixes for the existing workflows.
**4. Test:** I'll try to use a tool such as `act` to test the github actions on my local env, in case it doesn't work for this project I'll test the changes on my forked repo actions before creating the PR.
**5. Monitor:** Monitor the actions on the repo once the PR has been merged.

### Experience with ci/cd
Full Stack Software Engineer with over 4.5 years of experience. I have contributed to the CI/CD of some projects (carbonable, influence sdk) through onlydust, feel free to check out my devops contributions.

### ETA
This could vary depending on the difficulty of the issues it has right not, but I estimate 3 days at the most.

**Comment by ShantelPeters** [comment] 2024-09-05 14:57
I will love to work on this.

**Comment by lindsaymoralesb** [comment] 2024-09-26 17:56
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Lindsay - Software Engineer with over 4.5 years of experience. I’ve already contributed to this project before.

I’ve also had the opportunity to help a couple of other projects (carbonable and influence sdk) with their ci cd issues.

### How I plan on tackling this issue
1. Review the current state: Review the existing workflows and check the ci/cd logs under GitHub actions to spot where the issue is happening.
2. Review project: Identify components, dependencies, and their interaction on the ci/cd and commands (test, run, install, etc).
3. Update the workflows: Make the necessary fixes for the existing workflows.
4. Test: I'll try to use a tool such as act to test the github actions on my local env, in case it doesn't work for this project I'll test the changes on my forked repo actions before creating the PR.
5. Monitor: Monitor the actions on the repo once the PR has been merged.

ETA: could vary depending on the complexity of the issues found on the workflow, but I estimate 2-3 days at most.

**Closed** 2024-10-04 21:00 UTC
Labels: good first issue, help wanted, fix, ODHack8
