### ISSUE TITLE
React native routing and deep linking with navigator

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#130] opened 2024-09-25 19:43 UTC
# Description

React native routing and deep linking with navigator.
At this moment, the web React native redirect every time to the first screen in the navigator.

We want to have the possibilities to directly go this page like a Nostr profile or whatever.

# Todo
- [ ] Fix deep linking in Router.tsx
- [ ] Fix navigator routing
- [ ] Clean navigators
- [ ] Fix screens

**Comment by ShantelPeters** [comment] 2024-09-25 19:43
Hi

**Comment by od-hunter** [comment] 2024-09-25 19:43
H

**Comment by NueloSE** [comment] 2024-09-25 19:54
@MSghais kindly assign me ETA 2days

**Comment by martinvibes** [comment] 2024-09-25 20:47
hello @MSghais i would love to work on this issue

**Comment by CollinsC1O** [comment] 2024-09-26 07:56
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hello I'm a frontend and also a blockchain developer and I would love to jump on this issue

**Comment by petersdt** [comment] 2024-09-26 07:57
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
i am a frontend developer with experience using typescript for typesafety and js. kindly assign me


### How I plan on tackling this issue
1. i currently understand how the navigator works

**Comment by zleypner** [comment] 2024-09-26 07:57
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I’m a front-end developer with 3 years of experience transitioning to Web3, and I would love to make my first contribution to this project. I'm excited to take on this issue to challenge myself, learn, and contribute to the project's success.  I'm also a member of the Dojo Coding community, looking forward to applying my skills in this new space while I grow and contribute to the community.

### How I plan on tackling this issue
First, I would investigate how routing is currently set up in the project. I need to understand how the navigator initializes and why it's always redirecting to the first screen. This likely has something to do with the initial route configuration or how deep linking is being handled.
I'll configure deep linking so the app can navigate directly to specific pages like a Nostr profile or any other destination. This involves making sure the app can parse URLs properly and direct users to the correct screen based on the link. I'll look into the Router.tsx file to ensure it handles incoming URLs and routes them to the right screen.
Since the problem lies in the navigator always defaulting to the first screen, I’ll modify the logic so it checks for deep links or saved navigation states when the app initializes. This will allow the app to open directly to the screen specified by the deep link, rather than always starting at the first screen.
I'll review the current navigators and clean up any unnecessary or redundant configurations. The goal is to ensure a clear and efficient navigation flow, which will also help with maintaining the deep linking functionality. This step might involve consolidating routes and simplifying the overall structure.
I'll make sure each screen can handle incoming parameters from deep links. For example, if I’m navigating to a Nostr profile, the screen should be able to extract the profile ID or any other necessary data from the URL and render the correct content.
Once the changes are made, I’ll thoroughly test the deep linking functionality by simulating different deep link scenarios, like entering URLs directly in the browser or using universal links on mobile. I want to ensure that the app reliably navigates to the correct screens in all cases.
If I run into any problems or questions, I’ll reach out to the maintainers for assistance.

**Comment by od-hunter** [comment] 2024-09-26 08:18
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Please can I be assigned this issue? This would be my first time contributing to this ecosystem and I’d love to be given the opportunity. I am a blockchain Developer, and my experience includes html, css, react, JavaScript,TypeScript and solidity and Cairo.

### How I plan on tackling this issue
To solve issue, I’d take the following steps:

1.⁠ ⁠First of all, I’ll fix Deep Linking in Router.tsx (by mapping routes to URLs in the linking object and ensuring correct path handling for specific screens like Nostr profiles).
2.⁠ ⁠I’ll ensure the navigator hierarchy is properly set up to handle deep links, passing parameters to the correct screen.
3.⁠ ⁠I’ll simplify and clean up unnecessary or redundant code in the navigators for better maintainability.
4.⁠ ⁠I’ll ensure screens correctly receive and handle route parameters (e.g., nostrId) passed via deep links.
5.⁠ ⁠I’ll verify deep linking works on all platforms and different scenarios (web, Android, iOS) for proper routing behavior.

Please kindly assign.

**Comment by ShantelPeters** [comment] 2024-09-26 08:26
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a frontend developer with vast experience using typescript for typesafety and javascript . kindly assign me i am available to work please

### How I plan on tackling this issue
I would approach the problem by doing the following:

1. Deep Linking in Router.tsx: Ensure the deep linking setup correctly parses URLs and routes to the desired screen.
2. Navigator Routing: Check if the initial route is properly configured and if conditional logic forces navigation to the first screen.
3. Clean Navigators: Simplify navigator structure by removing redundant configurations.
4. Fix Screens: Ensure each screen's routing path is well-defined and accessible through deep links.

**Comment by MatiasAchucarro** [comment] 2024-09-26 08:39
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, C# with .NET Entity Framework, and more. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration.

I have already made a contribution to the open-source ecosystem, and I am eager to engage in more projects, particularly those involving Cairo.

### How I plan on tackling this issue
To resolve routing and deep linking issues in React Native, first, configure deep linking correctly in Router.tsx, mapping URL routes to the app screens. Ensure the navigator is set up to handle these routes without redirecting to the main screen.
Clean up the navigation logic to avoid unnecessary redirections and verify that each screen component is properly implemented and registered. Conduct tests with different deep links to ensure each one directs to the correct screen.

**Comment by Benjtalkshow** [comment] 2024-09-26 09:15
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
As a full-stack JavaScript developer with solid experience in using React and Expo, I'm well-prepared to handle the current navigation problems. My background in these technologies means I understand how to create smooth user experiences, and I can efficiently address the routing issue we’re facing.

### How I plan on tackling this issue
First, I’ll focus on fixing the deep linking in Router.tsx. This will allow users to directly access specific pages, like a Nostr profile, instead of always going back to the first screen in the navigator. I will review how deep linking is currently set up to ensure the app routes correctly based on the links being used.

Next, I’ll improve the navigator routing to ensure that transitions between screens work properly. I’ll clean up any unnecessary navigators to make the navigation system simple and easy to follow.

Once I’ve fixed the routing, I’ll check all the screens to ensure they work well with the new setup. This includes making sure that each screen loads correctly when accessed via deep links and behaves as expected when navigating within the app.

After making these changes, I’ll thoroughly test the routing and deep linking to ensure everything works smoothly. This will involve checking how the app handles different deep links and how it navigates between pages. Finally, I’ll tidy up the code to make sure the navigator and router components are efficient and easy to maintain.

**Comment by martinvibes** [comment] 2024-09-26 10:02
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged

hello i am a frontend dev and blockchain developer
please can i work on this issue :) and would love to be a contributor



### How I plan on tackling this issue
Review Existing Code: Understand the current setup in Router.tsx to identify issues.

Fix Deep Linking: Update the deep linking configuration to ensure correct screen navigation from URLs.

Enhance Navigator Routing: Refactor the navigator configuration to handle routes and components properly.

Clean Up Navigators: Simplify the navigator structure for better readability and maintainability.

Verify Screens: Ensure all screens are correctly defined and accessible via the navigator.

Test Changes: Conduct thorough testing to confirm deep linking and navigation work as intended.

Update Documentation: Revise documentation to reflect any changes made for future reference.

**Comment by MSghais** [comment] 2024-09-26 10:15
Someone have an ETA please?

**Comment by Jemiiah** [comment] 2024-10-03 10:25
I would love to work on this issue @MSghais

**Comment by lindsaymoralesb** [comment] 2024-10-03 15:07
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Lindsay - Software Engineer with almost 5 years of exp. Already contributed to this project several times.

### How I plan on tackling this issue
Most of my exp is with react and react native, and I have also had the chance to work with Deep Linking (and solve some strange issues as this is).
I'll start by using the urls examples shared and debugging the app, to see where exactly is the issue happening.

**Closed** 2024-10-06 22:07 UTC
Labels: enhancement, good first issue, help wanted, frontend, urgent, ODHack8, mobile
